name: Test changes
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
jobs:
  test:
    name: Pull Request
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout the code
        uses: actions/checkout@v4
      -
        name: Install and configure Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.7
      -
        name: Run tests
        run: |
          go test -v ./...
