name: Test changes
on:
  pull_request:
    branches:
      - main
      - 'v*'
jobs:
  test:
    name: Pull Request
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Install and configure Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.7
      -
        name: Run tests
        run: |
          go test -v ./...
      -
        name: Create snapshot
        run: |
          goreleaser build --parallelism 2 --rm-dist --snapshot --timeout 1h
